/* ══════════════════════════════════════════════════════════════
   Grimorio — creature dell'SRD 5.1 (OGL 1.0a)
   Selezione delle creature che servono davvero al tavolo: tutte le
   bestie usate da forma selvatica, famigli e compagni animali, più
   i mostri di uso comune ai livelli bassi e medi.
   Nomi e descrizioni tradotti; le statistiche sono dati di gioco.
   ab: [FOR, DES, COS, INT, SAG, CAR] · cr: grado di sfida
   ══════════════════════════════════════════════════════════════ */
const SRD_MONSTERS = [
/* ─── Bestie minuscole: famigli ─── */
{id:'bat',n:'Bat',it:'Pipistrello',sz:'Minuscola',t:'bestia',ac:12,hp:1,hd:'1d4-1',sp:'1,5 m, volare 9 m',ab:[2,15,8,2,12,4],sen:'Udito cieco 18 m, Percezione passiva 11',cr:'0',fam:true,
 tr:[['Udito cieco','Non può usare la vista, ma percepisce tutto entro 18 m con l\'eco.'],['Udito acuto','Vantaggio alle prove di Percezione basate sull\'udito.']],
 act:[['Morso','+0','1 perforante','']]},
{id:'cat',n:'Cat',it:'Gatto',sz:'Minuscola',t:'bestia',ac:12,hp:2,hd:'1d4',sp:'12 m, scalare 9 m',ab:[3,15,10,3,12,7],sk:{perception:3,stealth:4},sen:'Percezione passiva 13',cr:'0',fam:true,
 tr:[['Olfatto acuto','Vantaggio alle prove di Percezione basate sull\'olfatto.']],
 act:[['Artigli','+0','1 tagliente','']]},
{id:'crab',n:'Crab',it:'Granchio',sz:'Minuscola',t:'bestia',ac:11,hp:2,hd:'1d4',sp:'6 m, nuotare 6 m',ab:[2,11,10,1,8,2],sk:{stealth:2},sen:'Visione cieca 9 m, Percezione passiva 9',cr:'0',fam:true,
 tr:[['Anfibio','Respira aria e acqua.']],
 act:[['Chela','+0','1 contundente','']]},
{id:'frog',n:'Frog',it:'Rana',sz:'Minuscola',t:'bestia',ac:11,hp:1,hd:'1d4-1',sp:'6 m, nuotare 6 m',ab:[1,13,8,1,8,3],sk:{perception:1,stealth:3},sen:'Scurovisione 9 m, Percezione passiva 11',cr:'0',fam:true,
 tr:[['Anfibio','Respira aria e acqua.'],['Salto','Salta fino a 3 m in lungo e 1,5 m in alto.']],act:[]},
{id:'hawk',n:'Hawk',it:'Falco',sz:'Minuscola',t:'bestia',ac:13,hp:1,hd:'1d4-1',sp:'3 m, volare 18 m',ab:[5,16,8,2,14,6],sk:{perception:4},sen:'Percezione passiva 14',cr:'0',fam:true,
 tr:[['Vista acuta','Vantaggio alle prove di Percezione basate sulla vista.']],
 act:[['Artigli','+5','1 tagliente','']]},
{id:'lizard',n:'Lizard',it:'Lucertola',sz:'Minuscola',t:'bestia',ac:10,hp:2,hd:'1d4',sp:'6 m, scalare 6 m',ab:[2,11,10,1,8,3],sen:'Scurovisione 9 m, Percezione passiva 9',cr:'0',fam:true,
 act:[['Morso','+0','1 perforante','']]},
{id:'octopus',n:'Octopus',it:'Polpo',sz:'Piccola',t:'bestia',ac:12,hp:3,hd:'1d6',sp:'1,5 m, nuotare 9 m',ab:[4,15,11,3,10,4],sk:{perception:2,stealth:4},sen:'Scurovisione 9 m, Percezione passiva 12',cr:'0',fam:true,
 tr:[['Respirare acqua','Respira solo sott\'acqua; resiste 30 minuti fuori.'],['Mimetismo','Vantaggio a nascondersi.']],
 act:[['Tentacoli','+4','1 contundente','Il bersaglio è afferrato (CD 10)'],['Nube d\'inchiostro','—','—','Ricarica dopo un riposo breve: oscura 1,5 m e permette di scattare']]},
{id:'owl',n:'Owl',it:'Gufo',sz:'Minuscola',t:'bestia',ac:11,hp:1,hd:'1d4-1',sp:'1,5 m, volare 18 m',ab:[3,13,8,2,12,7],sk:{perception:3,stealth:3},sen:'Scurovisione 36 m, Percezione passiva 13',cr:'0',fam:true,
 tr:[['Volo silenzioso','Vantaggio a nascondersi quando vola.']],
 act:[['Artigli','+3','1 tagliente','']]},
{id:'poisonous-snake',n:'Poisonous Snake',it:'Serpente velenoso',sz:'Minuscola',t:'bestia',ac:13,hp:2,hd:'1d4',sp:'9 m, nuotare 9 m',ab:[2,16,11,1,10,3],sen:'Visione cieca 3 m, Percezione passiva 10',cr:'1/8',fam:true,
 act:[['Morso','+5','1 perforante + 2d4 veleno (TS COS CD 10 dimezza)','']]},
{id:'rat',n:'Rat',it:'Ratto',sz:'Minuscola',t:'bestia',ac:10,hp:1,hd:'1d4-1',sp:'6 m',ab:[2,11,9,2,10,4],sen:'Scurovisione 9 m, Percezione passiva 10',cr:'0',fam:true,
 tr:[['Olfatto acuto','Vantaggio alle prove di Percezione basate sull\'olfatto.']],
 act:[['Morso','+0','1 perforante','']]},
{id:'raven',n:'Raven',it:'Corvo',sz:'Minuscola',t:'bestia',ac:12,hp:1,hd:'1d4-1',sp:'3 m, volare 15 m',ab:[2,14,8,2,12,6],sk:{perception:3},sen:'Percezione passiva 13',cr:'0',fam:true,
 tr:[['Imitazione','Sa imitare suoni semplici (INT CD 10 per smascherarlo).']],
 act:[['Becco','+4','1 perforante','']]},
{id:'spider',n:'Spider',it:'Ragno',sz:'Minuscola',t:'bestia',ac:12,hp:1,hd:'1d4-1',sp:'6 m, scalare 6 m',ab:[2,14,8,1,10,2],sk:{stealth:4},sen:'Scurovisione 9 m, Percezione passiva 10',cr:'0',fam:true,
 tr:[['Camminare sulle ragnatele','Si muove sulle ragnatele senza impedimenti e scala superfici difficili.']],
 act:[['Morso','+4','1 perforante + 1d4 veleno (TS COS CD 9 dimezza)','']]},
{id:'weasel',n:'Weasel',it:'Donnola',sz:'Minuscola',t:'bestia',ac:13,hp:1,hd:'1d4-1',sp:'9 m',ab:[3,16,8,2,12,3],sk:{perception:3,stealth:5},sen:'Percezione passiva 13',cr:'0',fam:true,
 tr:[['Udito e olfatto acuti','Vantaggio alle prove di Percezione basate su udito e olfatto.']],
 act:[['Morso','+5','1 perforante','']]},

/* ─── Bestie: forma selvatica e compagni animali ─── */
{id:'wolf',n:'Wolf',it:'Lupo',sz:'Media',t:'bestia',ac:13,hp:11,hd:'2d8+2',sp:'12 m',ab:[12,15,12,3,12,6],sk:{perception:3,stealth:4},sen:'Percezione passiva 13',cr:'1/4',beast:true,
 tr:[['Udito e olfatto acuti','Vantaggio alle prove di Percezione basate su udito e olfatto.'],['Tattica del branco','Vantaggio all\'attacco se un alleato è entro 1,5 m dal bersaglio.']],
 act:[['Morso','+4','2d4+2 perforanti','TS Forza CD 11 o il bersaglio cade prono']]},
{id:'dire-wolf',n:'Dire Wolf',it:'Lupo terribile',sz:'Grande',t:'bestia',ac:14,hp:37,hd:'5d10+10',sp:'15 m',ab:[17,15,15,3,12,7],sk:{perception:3,stealth:4},sen:'Percezione passiva 13',cr:'1',beast:true,
 tr:[['Udito e olfatto acuti','Vantaggio alle prove di Percezione basate su udito e olfatto.'],['Tattica del branco','Vantaggio all\'attacco se un alleato è entro 1,5 m dal bersaglio.']],
 act:[['Morso','+5','2d6+3 perforanti','TS Forza CD 13 o il bersaglio cade prono']]},
{id:'black-bear',n:'Black Bear',it:'Orso nero',sz:'Media',t:'bestia',ac:11,hp:19,hd:'3d8+6',sp:'12 m, scalare 9 m',ab:[15,10,14,2,12,7],sk:{perception:3},sen:'Percezione passiva 13',cr:'1/2',beast:true,
 tr:[['Olfatto acuto','Vantaggio alle prove di Percezione basate sull\'olfatto.']],
 act:[['Morso','+3','1d6+2 perforanti',''],['Artigli','+3','2d4+2 taglienti','']]},
{id:'brown-bear',n:'Brown Bear',it:'Orso bruno',sz:'Grande',t:'bestia',ac:11,hp:34,hd:'4d10+12',sp:'12 m, scalare 9 m',ab:[19,10,16,2,13,7],sk:{perception:3},sen:'Percezione passiva 13',cr:'1',beast:true,
 tr:[['Olfatto acuto','Vantaggio alle prove di Percezione basate sull\'olfatto.']],
 act:[['Morso','+5','1d8+4 perforanti',''],['Artigli','+5','2d6+4 taglienti','']]},
{id:'polar-bear',n:'Polar Bear',it:'Orso polare',sz:'Grande',t:'bestia',ac:12,hp:42,hd:'5d10+15',sp:'12 m, nuotare 9 m',ab:[20,10,16,2,13,7],sk:{perception:3},sen:'Percezione passiva 13',cr:'2',beast:true,
 tr:[['Olfatto acuto','Vantaggio alle prove di Percezione basate sull\'olfatto.']],
 act:[['Morso','+7','1d8+5 perforanti',''],['Artigli','+7','2d6+5 taglienti','']]},
{id:'boar',n:'Boar',it:'Cinghiale',sz:'Media',t:'bestia',ac:11,hp:11,hd:'2d8+2',sp:'12 m',ab:[13,11,12,2,9,5],sen:'Percezione passiva 9',cr:'1/4',beast:true,
 tr:[['Carica','Se si muove di 6 m e colpisce, +1d6 danni e TS Forza CD 11 o prono.'],['Grinta','Se scende a 0 PF resta a 1 PF (1/riposo lungo).']],
 act:[['Zanne','+3','1d6+1 taglienti','']]},
{id:'panther',n:'Panther',it:'Pantera',sz:'Media',t:'bestia',ac:12,hp:13,hd:'3d8',sp:'15 m, scalare 12 m',ab:[14,15,10,3,14,7],sk:{perception:4,stealth:6},sen:'Percezione passiva 14',cr:'1/4',beast:true,
 tr:[['Olfatto acuto','Vantaggio alle prove di Percezione basate sull\'olfatto.'],['Balzo','Dopo 6 m di corsa e un colpo di artigli: TS Forza CD 12 o prono, con morso bonus.']],
 act:[['Morso','+4','1d6+2 perforanti',''],['Artigli','+4','1d4+2 taglienti','']]},
{id:'tiger',n:'Tiger',it:'Tigre',sz:'Grande',t:'bestia',ac:12,hp:37,hd:'5d10+10',sp:'12 m',ab:[17,15,14,3,12,8],sk:{perception:3,stealth:4},sen:'Scurovisione 18 m, Percezione passiva 13',cr:'1',beast:true,
 tr:[['Olfatto acuto','Vantaggio alle prove di Percezione basate sull\'olfatto.'],['Balzo','Dopo 6 m di corsa e artigli: TS Forza CD 13 o prono, con morso bonus.']],
 act:[['Morso','+5','1d10+3 perforanti',''],['Artigli','+5','1d8+3 taglienti','']]},
{id:'lion',n:'Lion',it:'Leone',sz:'Grande',t:'bestia',ac:12,hp:26,hd:'4d10+4',sp:'15 m',ab:[17,15,13,3,12,8],sk:{perception:3,stealth:6},sen:'Percezione passiva 13',cr:'1',beast:true,
 tr:[['Olfatto acuto','Vantaggio alle prove di Percezione basate sull\'olfatto.'],['Tattica del branco','Vantaggio all\'attacco se un alleato è adiacente al bersaglio.'],['Balzo','Dopo 6 m di corsa: TS Forza CD 13 o prono, con morso bonus.']],
 act:[['Morso','+5','1d8+3 perforanti',''],['Artigli','+5','1d6+3 taglienti','']]},
{id:'crocodile',n:'Crocodile',it:'Coccodrillo',sz:'Grande',t:'bestia',ac:12,hp:19,hd:'3d10+3',sp:'6 m, nuotare 9 m',ab:[15,10,13,2,10,5],sk:{stealth:2},sen:'Percezione passiva 10',cr:'1/2',beast:true,
 tr:[['Trattenere il respiro','Trattiene il respiro per 15 minuti.']],
 act:[['Morso','+4','1d10+2 perforanti','Il bersaglio è afferrato (CD 12) e trattenuto']]},
{id:'giant-crocodile',n:'Giant Crocodile',it:'Coccodrillo gigante',sz:'Enorme',t:'bestia',ac:14,hp:85,hd:'9d12+27',sp:'9 m, nuotare 15 m',ab:[21,9,17,2,10,7],sk:{stealth:5},sen:'Percezione passiva 10',cr:'5',beast:true,
 act:[['Morso','+8','3d10+5 perforanti','Afferrato (CD 16) e trattenuto'],['Coda','+8','2d8+5 contundenti','TS Forza CD 16 o prono']]},
{id:'giant-spider',n:'Giant Spider',it:'Ragno gigante',sz:'Grande',t:'bestia',ac:14,hp:26,hd:'4d10+4',sp:'9 m, scalare 9 m',ab:[14,16,12,2,11,4],sk:{stealth:7},sen:'Visione cieca 3 m, Scurovisione 18 m, Percezione passiva 10',cr:'1',beast:true,
 tr:[['Camminare sulle ragnatele','Scala superfici difficili senza prove.'],['Percezione della ragnatela','Percepisce ogni cosa in contatto con la stessa ragnatela.']],
 act:[['Morso','+5','1d8+3 perforanti + 2d8 veleno (TS COS CD 11 dimezza)',''],['Ragnatela','+5','—','Bersaglio trattenuto, CA 10, 5 PF (ricarica 5-6)']]},
{id:'giant-rat',n:'Giant Rat',it:'Ratto gigante',sz:'Piccola',t:'bestia',ac:12,hp:7,hd:'2d6',sp:'9 m',ab:[7,15,11,2,10,4],sen:'Scurovisione 18 m, Percezione passiva 10',cr:'1/8',beast:true,
 tr:[['Olfatto acuto','Vantaggio alle prove di Percezione basate sull\'olfatto.'],['Tattica del branco','Vantaggio all\'attacco se un alleato è adiacente al bersaglio.']],
 act:[['Morso','+4','1d4+2 perforanti','']]},
{id:'constrictor-snake',n:'Constrictor Snake',it:'Serpente costrittore',sz:'Grande',t:'bestia',ac:12,hp:13,hd:'2d10+2',sp:'9 m, nuotare 9 m',ab:[15,14,12,1,10,3],sen:'Visione cieca 3 m, Percezione passiva 10',cr:'1/4',beast:true,
 act:[['Morso','+4','1d6+2 perforanti',''],['Costrizione','+4','1d8+2 contundenti','Afferrato (CD 14) e trattenuto']]},
{id:'giant-eagle',n:'Giant Eagle',it:'Aquila gigante',sz:'Grande',t:'bestia',ac:13,hp:26,hd:'4d10+4',sp:'3 m, volare 24 m',ab:[16,17,13,8,14,10],sk:{perception:4},sen:'Percezione passiva 14',cr:'1',beast:true,
 tr:[['Vista acuta','Vantaggio alle prove di Percezione basate sulla vista.']],
 act:[['Becco','+5','1d6+3 perforanti',''],['Artigli','+5','2d6+3 taglienti','']]},
{id:'eagle',n:'Eagle',it:'Aquila',sz:'Piccola',t:'bestia',ac:12,hp:3,hd:'1d6',sp:'3 m, volare 18 m',ab:[6,15,10,2,14,7],sk:{perception:4},sen:'Percezione passiva 14',cr:'0',beast:true,
 tr:[['Vista acuta','Vantaggio alle prove di Percezione basate sulla vista.']],
 act:[['Artigli','+4','1d4+2 taglienti','']]},
{id:'giant-owl',n:'Giant Owl',it:'Gufo gigante',sz:'Grande',t:'bestia',ac:12,hp:19,hd:'3d10+3',sp:'1,5 m, volare 18 m',ab:[13,15,12,8,13,10],sk:{perception:5,stealth:4},sen:'Scurovisione 36 m, Percezione passiva 15',cr:'1/4',beast:true,
 tr:[['Volo silenzioso','Vantaggio a nascondersi in volo.'],['Vista acuta','Vantaggio alle prove di Percezione basate sulla vista.']],
 act:[['Artigli','+3','2d6+1 taglienti','']]},
{id:'mastiff',n:'Mastiff',it:'Mastino',sz:'Media',t:'bestia',ac:12,hp:5,hd:'1d8+1',sp:'12 m',ab:[13,14,12,3,12,7],sk:{perception:3},sen:'Percezione passiva 13',cr:'1/8',beast:true,
 tr:[['Udito e olfatto acuti','Vantaggio alle prove di Percezione basate su udito e olfatto.']],
 act:[['Morso','+3','1d6+1 perforanti','TS Forza CD 11 o prono']]},
{id:'riding-horse',n:'Riding Horse',it:'Cavallo da sella',sz:'Grande',t:'bestia',ac:10,hp:13,hd:'2d10+2',sp:'18 m',ab:[16,10,12,2,11,7],sen:'Percezione passiva 10',cr:'1/4',beast:true,
 act:[['Zoccoli','+5','2d4+3 contundenti','']]},
{id:'warhorse',n:'Warhorse',it:'Cavallo da guerra',sz:'Grande',t:'bestia',ac:11,hp:19,hd:'3d10+3',sp:'18 m',ab:[18,12,13,2,12,7],sen:'Percezione passiva 11',cr:'1/2',beast:true,
 tr:[['Carica travolgente','Se corre 6 m e colpisce: TS Forza CD 14 o prono.']],
 act:[['Zoccoli','+6','2d6+4 contundenti','']]},
{id:'elk',n:'Elk',it:'Alce',sz:'Grande',t:'bestia',ac:10,hp:13,hd:'2d10+2',sp:'15 m',ab:[16,10,12,2,10,6],sen:'Percezione passiva 10',cr:'1/4',beast:true,
 tr:[['Carica','Se corre 6 m e incorna: +1d6 e TS Forza CD 13 o prono.']],
 act:[['Corna','+5','1d6+3 contundenti',''],['Zoccoli','+5','2d4+3 contundenti','solo contro bersagli proni']]},
{id:'giant-goat',n:'Giant Goat',it:'Capra gigante',sz:'Grande',t:'bestia',ac:11,hp:19,hd:'3d10+3',sp:'12 m',ab:[17,11,12,3,12,6],sen:'Percezione passiva 11',cr:'1/2',beast:true,
 tr:[['Carica','Se corre 6 m e incorna: +2d4 e TS Forza CD 13 o prono.'],['Passo sicuro','Vantaggio contro l\'essere spinto o fatto cadere prono.']],
 act:[['Incornata','+5','2d4+3 contundenti','']]},
{id:'ape',n:'Ape',it:'Scimmione',sz:'Media',t:'bestia',ac:12,hp:19,hd:'3d8+6',sp:'9 m, scalare 9 m',ab:[16,14,14,6,12,7],sk:{athletics:5,perception:3},sen:'Percezione passiva 13',cr:'1/2',beast:true,
 act:[['Pugno','+5','1d6+3 contundenti',''],['Sasso','+5','1d6+3 contundenti','gittata 7,5/15 m']]},
{id:'giant-toad',n:'Giant Toad',it:'Rospo gigante',sz:'Grande',t:'bestia',ac:11,hp:39,hd:'6d10+6',sp:'6 m, nuotare 12 m',ab:[15,13,13,2,10,3],sen:'Scurovisione 9 m, Percezione passiva 10',cr:'1',beast:true,
 tr:[['Anfibio','Respira aria e acqua.'],['Salto in piedi','Il salto non costa movimento extra.']],
 act:[['Morso','+4','1d10+2 perforanti + 1d10 veleno','Afferrato (CD 13) e può essere inghiottito']]},
{id:'giant-hyena',n:'Giant Hyena',it:'Iena gigante',sz:'Grande',t:'bestia',ac:12,hp:45,hd:'6d10+12',sp:'15 m',ab:[16,14,14,2,12,7],sk:{perception:3},sen:'Percezione passiva 13',cr:'1',beast:true,
 tr:[['Frenesia','Se riduce una creatura a 0 PF può mordere come azione bonus.']],
 act:[['Morso','+5','2d6+3 perforanti','']]},
{id:'giant-shark',n:'Giant Shark',it:'Squalo gigante',sz:'Enorme',t:'bestia',ac:13,hp:126,hd:'11d12+55',sp:'nuotare 15 m',ab:[23,11,21,1,10,5],sk:{perception:3},sen:'Visione cieca 18 m, Percezione passiva 13',cr:'5',beast:true,
 tr:[['Respirare acqua','Respira solo sott\'acqua.']],
 act:[['Morso','+9','3d10+6 perforanti','']]},
{id:'giant-octopus',n:'Giant Octopus',it:'Piovra gigante',sz:'Grande',t:'bestia',ac:11,hp:52,hd:'8d10+8',sp:'3 m, nuotare 18 m',ab:[17,13,13,4,10,4],sk:{perception:4,stealth:5},sen:'Scurovisione 18 m, Percezione passiva 14',cr:'1',beast:true,
 tr:[['Respirare acqua','Fuori dall\'acqua resiste 1 ora.'],['Mimetismo','Vantaggio a nascondersi.']],
 act:[['Tentacoli','+5','2d6+3 contundenti','Afferrato (CD 16) e trattenuto'],['Nube d\'inchiostro','—','—','Oscura un cubo di 6 m (ricarica dopo un riposo)']]},
{id:'elephant',n:'Elephant',it:'Elefante',sz:'Enorme',t:'bestia',ac:12,hp:76,hd:'8d12+24',sp:'12 m',ab:[22,9,17,3,11,6],sen:'Percezione passiva 10',cr:'4',beast:true,
 tr:[['Carica travolgente','Se corre 6 m e incorna: +2d6 e TS Forza CD 12 o prono.'],['Calpestare','Attacco bonus con gli zoccoli su un bersaglio prono.']],
 act:[['Incornata','+8','3d8+6 contundenti',''],['Zoccoli','+8','3d10+6 contundenti','solo contro bersagli proni']]},
{id:'giant-boar',n:'Giant Boar',it:'Cinghiale gigante',sz:'Grande',t:'bestia',ac:12,hp:42,hd:'5d10+15',sp:'12 m',ab:[17,10,16,2,7,5],sen:'Percezione passiva 8',cr:'2',beast:true,
 tr:[['Carica','Se corre 6 m e colpisce: +2d6 e TS Forza CD 13 o prono.'],['Grinta','Se scende a 0 PF resta a 1 PF (1/riposo lungo).']],
 act:[['Zanne','+5','2d6+3 taglienti','']]},

/* ─── Mostri di uso comune ─── */
{id:'goblin',n:'Goblin',it:'Goblin',sz:'Piccola',t:'umanoide',ac:15,hp:7,hd:'2d6',sp:'9 m',ab:[8,14,10,10,8,8],sk:{stealth:6},sen:'Scurovisione 18 m, Percezione passiva 9',cr:'1/4',
 tr:[['Fuga agile','Può Disimpegnarsi o Nascondersi come azione bonus.']],
 act:[['Scimitarra','+4','1d6+2 taglienti',''],['Arco corto','+4','1d6+2 perforanti','gittata 24/96 m']]},
{id:'hobgoblin',n:'Hobgoblin',it:'Hobgoblin',sz:'Media',t:'umanoide',ac:18,hp:11,hd:'2d8+2',sp:'9 m',ab:[13,12,12,10,10,9],sen:'Scurovisione 18 m, Percezione passiva 10',cr:'1/2',
 tr:[['Vantaggio marziale','+2d6 danni una volta per turno contro un nemico affiancato da un alleato.']],
 act:[['Spada lunga','+3','1d8+1 taglienti',''],['Arco lungo','+3','1d8+1 perforanti','gittata 45/180 m']]},
{id:'orc',n:'Orc',it:'Orco',sz:'Media',t:'umanoide',ac:13,hp:15,hd:'2d8+6',sp:'9 m',ab:[16,12,16,7,11,10],sk:{intimidation:2},sen:'Scurovisione 18 m, Percezione passiva 10',cr:'1/2',
 tr:[['Aggressivo','Azione bonus: si muove verso un nemico che può vedere.']],
 act:[['Ascia bipenne','+5','1d12+3 taglienti',''],['Giavellotto','+5','1d6+3 perforanti','gittata 9/36 m']]},
{id:'kobold',n:'Kobold',it:'Coboldo',sz:'Piccola',t:'umanoide',ac:12,hp:5,hd:'2d6-2',sp:'9 m',ab:[7,15,9,8,7,8],sen:'Scurovisione 18 m, Percezione passiva 8',cr:'1/8',
 tr:[['Sensibile alla luce solare','Svantaggio alla vista sotto la luce del sole.'],['Tattica di branco','Vantaggio all\'attacco se un alleato è adiacente al bersaglio.']],
 act:[['Fionda','+4','1d4+2 contundenti','gittata 9/36 m'],['Pugnale','+4','1d4+2 perforanti','']]},
{id:'gnoll',n:'Gnoll',it:'Gnoll',sz:'Media',t:'umanoide',ac:15,hp:22,hd:'5d8',sp:'9 m',ab:[14,12,11,6,10,7],sen:'Scurovisione 18 m, Percezione passiva 10',cr:'1/2',
 tr:[['Frenesia','Se riduce una creatura a 0 PF può muoversi e mordere come azione bonus.']],
 act:[['Morso','+4','1d4+2 perforanti',''],['Lancia','+4','1d6+2 perforanti',''],['Arco lungo','+3','1d8+1 perforanti','']]},
{id:'bandit',n:'Bandit',it:'Bandito',sz:'Media',t:'umanoide',ac:12,hp:11,hd:'2d8+2',sp:'9 m',ab:[11,12,12,10,10,10],sen:'Percezione passiva 10',cr:'1/8',
 act:[['Scimitarra','+3','1d6+1 taglienti',''],['Balestra leggera','+3','1d8+1 perforanti','gittata 24/96 m']]},
{id:'bandit-captain',n:'Bandit Captain',it:'Capitano dei banditi',sz:'Media',t:'umanoide',ac:15,hp:65,hd:'10d8+20',sp:'9 m',ab:[15,16,14,14,11,14],sk:{athletics:4,deception:4},sen:'Percezione passiva 10',cr:'2',
 tr:[['Parata','Reazione: +2 alla CA contro un attacco in mischia.']],
 act:[['Scimitarra','+5','1d6+3 taglienti','due attacchi'],['Pugnale','+5','1d4+3 perforanti','']]},
{id:'guard',n:'Guard',it:'Guardia',sz:'Media',t:'umanoide',ac:16,hp:11,hd:'2d8+2',sp:'9 m',ab:[13,12,12,10,11,10],sk:{perception:2},sen:'Percezione passiva 12',cr:'1/8',
 act:[['Lancia','+3','1d6+1 perforanti','']]},
{id:'veteran',n:'Veteran',it:'Veterano',sz:'Media',t:'umanoide',ac:17,hp:58,hd:'9d8+18',sp:'9 m',ab:[16,13,14,10,11,10],sk:{athletics:5,perception:2},sen:'Percezione passiva 12',cr:'3',
 act:[['Spada lunga','+5','1d8+3 taglienti','due attacchi'],['Spada corta','+5','1d6+3 perforanti',''],['Balestra pesante','+3','1d10+1 perforanti','']]},
{id:'berserker',n:'Berserker',it:'Berserker',sz:'Media',t:'umanoide',ac:13,hp:67,hd:'9d8+27',sp:'9 m',ab:[16,12,17,9,11,9],sen:'Percezione passiva 10',cr:'2',
 tr:[['Spericolato','Può attaccare con vantaggio subendo attacchi con vantaggio fino al turno dopo.']],
 act:[['Ascia bipenne','+5','1d12+3 taglienti','']]},
{id:'cultist',n:'Cultist',it:'Cultista',sz:'Media',t:'umanoide',ac:12,hp:9,hd:'2d8',sp:'9 m',ab:[11,12,10,10,11,10],sk:{deception:2,religion:2},sen:'Percezione passiva 10',cr:'1/8',
 tr:[['Devozione oscura','Vantaggio contro l\'essere affascinato o spaventato.']],
 act:[['Scimitarra','+3','1d6+1 taglienti','']]},
{id:'priest',n:'Priest',it:'Sacerdote',sz:'Media',t:'umanoide',ac:13,hp:27,hd:'5d8+5',sp:'7,5 m',ab:[10,10,12,13,16,13],sk:{medicine:7,persuasion:3,religion:5},sen:'Percezione passiva 13',cr:'2',
 tr:[['Incantesimi','Chierico di 5° livello, CD 13: cura ferite, benedizione, luce spirituale…'],['Eminenza divina','Aggiunge 3d6 danni radiosi a un colpo spendendo uno slot.']],
 act:[['Mazza','+2','1d6 contundenti','']]},
{id:'mage',n:'Mage',it:'Mago',sz:'Media',t:'umanoide',ac:12,hp:40,hd:'9d8',sp:'9 m',ab:[9,14,11,17,12,11],sk:{arcana:6,history:6},sen:'Percezione passiva 11',cr:'6',
 tr:[['Incantesimi','Mago di 9° livello, CD 14, +6 all\'attacco: palla di fuoco, dardo incantato, scudo, volare…']],
 act:[['Pugnale','+5','1d4+2 perforanti','']]},
{id:'spy',n:'Spy',it:'Spia',sz:'Media',t:'umanoide',ac:12,hp:27,hd:'6d8',sp:'9 m',ab:[10,15,10,12,14,16],sk:{deception:5,perception:6,stealth:6},sen:'Percezione passiva 16',cr:'1',
 tr:[['Attacco furtivo','+2d6 danni una volta per turno con vantaggio o con un alleato adiacente.'],['Azione astuta','Scatto, Disimpegno o Nascondersi come azione bonus.']],
 act:[['Spada corta','+4','1d6+2 perforanti',''],['Balestra a mano','+4','1d6+2 perforanti','']]},
{id:'skeleton',n:'Skeleton',it:'Scheletro',sz:'Media',t:'non morto',ac:13,hp:13,hd:'2d8+4',sp:'9 m',ab:[10,14,15,6,8,5],sen:'Scurovisione 18 m, Percezione passiva 9',cr:'1/4',
 tr:[['Vulnerabilità','Vulnerabile ai danni contundenti; immune a veleno e sfinimento.']],
 act:[['Spada corta','+4','1d6+2 perforanti',''],['Arco corto','+4','1d6+2 perforanti','']]},
{id:'zombie',n:'Zombie',it:'Zombi',sz:'Media',t:'non morto',ac:8,hp:22,hd:'3d8+9',sp:'6 m',ab:[13,6,16,3,6,5],sen:'Scurovisione 18 m, Percezione passiva 8',cr:'1/4',
 tr:[['Tenacia dei non morti','Con un TS COS CD 5+danni resta a 1 PF invece di cadere.']],
 act:[['Colpo','+3','1d6+1 contundenti','']]},
{id:'ghoul',n:'Ghoul',it:'Ghoul',sz:'Media',t:'non morto',ac:12,hp:22,hd:'5d8',sp:'9 m',ab:[13,15,10,7,10,6],sen:'Scurovisione 18 m, Percezione passiva 10',cr:'1',
 tr:[['Immunità','Immune a veleno e all\'essere sfinito o affascinato.']],
 act:[['Morso','+2','2d6+2 perforanti',''],['Artigli','+4','2d4+2 taglienti','TS COS CD 10 o paralizzato per 1 minuto']]},
{id:'shadow',n:'Shadow',it:'Ombra',sz:'Media',t:'non morto',ac:12,hp:16,hd:'3d8+3',sp:'12 m',ab:[6,14,13,6,10,8],sk:{stealth:6},sen:'Scurovisione 18 m, Percezione passiva 10',cr:'1/2',
 tr:[['Amorfo','Passa in spazi larghi 2,5 cm senza rallentare.'],['Furtiva nell\'ombra','Si nasconde come azione bonus in penombra o oscurità.'],['Debolezza alla luce solare','Svantaggio a prove, attacchi e TS alla luce del sole.']],
 act:[['Tocco gelido','+4','2d6+2 necrotici','Riduce la Forza di 1d4: a 0 la vittima muore e diventa un\'ombra']]},
{id:'ogre',n:'Ogre',it:'Ogre',sz:'Grande',t:'gigante',ac:11,hp:59,hd:'7d10+21',sp:'12 m',ab:[19,8,16,5,7,7],sen:'Scurovisione 18 m, Percezione passiva 8',cr:'2',
 act:[['Mazza chiodata','+6','2d8+4 contundenti',''],['Giavellotto','+6','2d6+4 perforanti','']]},
{id:'troll',n:'Troll',it:'Troll',sz:'Grande',t:'gigante',ac:15,hp:84,hd:'8d10+40',sp:'9 m',ab:[18,13,20,7,9,7],sk:{perception:2},sen:'Scurovisione 18 m, Percezione passiva 12',cr:'5',
 tr:[['Rigenerazione','Recupera 10 PF all\'inizio del turno, a meno di danni da acido o fuoco.'],['Olfatto acuto','Vantaggio alle prove di Percezione basate sull\'olfatto.']],
 act:[['Morso','+7','1d6+4 perforanti',''],['Artigli','+7','2d6+4 taglienti','due attacchi']]},
{id:'hill-giant',n:'Hill Giant',it:'Gigante delle colline',sz:'Enorme',t:'gigante',ac:13,hp:105,hd:'10d12+40',sp:'12 m',ab:[21,8,19,5,9,6],sk:{perception:2},sen:'Percezione passiva 12',cr:'5',
 act:[['Randello','+8','3d8+5 contundenti','due attacchi'],['Masso','+8','3d10+5 contundenti','gittata 18/72 m']]},
{id:'owlbear',n:'Owlbear',it:'Orsogufo',sz:'Grande',t:'mostruosità',ac:13,hp:59,hd:'7d10+21',sp:'12 m',ab:[20,12,17,3,12,7],sk:{perception:3},sen:'Scurovisione 18 m, Percezione passiva 13',cr:'3',
 tr:[['Vista e olfatto acuti','Vantaggio alle prove di Percezione basate su vista e olfatto.']],
 act:[['Becco','+7','1d10+5 perforanti',''],['Artigli','+7','2d8+5 taglienti','']]},
{id:'harpy',n:'Harpy',it:'Arpia',sz:'Media',t:'mostruosità',ac:11,hp:38,hd:'7d8+7',sp:'6 m, volare 12 m',ab:[12,13,12,7,10,13],sen:'Percezione passiva 10',cr:'1',
 act:[['Artigli','+3','2d4+1 taglienti',''],['Randello','+3','1d4+1 contundenti',''],['Canto ammaliante','—','—','TS SAG CD 11 o affascinato e attirato verso l\'arpia']]},
{id:'dryad',n:'Dryad',it:'Driade',sz:'Media',t:'folletto',ac:11,hp:22,hd:'5d8',sp:'9 m',ab:[10,12,11,14,15,18],sk:{perception:4,stealth:5},sen:'Scurovisione 18 m, Percezione passiva 14',cr:'1',
 tr:[['Passo arboreo','Si teletrasporta 18 m fra due alberi.'],['Incantesimi innati','CD 14: arte druidica, intralciare, charme su persona, parlare con le piante.']],
 act:[['Randello','+2','1d4 contundenti','']]},
{id:'sprite',n:'Sprite',it:'Folletto',sz:'Minuscola',t:'folletto',ac:15,hp:2,hd:'1d4',sp:'3 m, volare 12 m',ab:[3,18,10,14,13,11],sk:{perception:3,stealth:8},sen:'Percezione passiva 13',cr:'1/4',
 act:[['Spada corta','+6','1 perforante',''],['Arco corto','+6','1 perforante + veleno','TS COS CD 10 o avvelenato; se fallisce di 5 privo di sensi'],['Percepire il cuore','—','—','Capisce le emozioni e l\'allineamento a contatto'],['Invisibilità','—','—','Diventa invisibile finché non attacca']]},
{id:'centaur',n:'Centaur',it:'Centauro',sz:'Grande',t:'mostruosità',ac:12,hp:45,hd:'6d10+12',sp:'15 m',ab:[18,14,14,9,13,11],sk:{athletics:6,perception:3,survival:3},sen:'Percezione passiva 13',cr:'2',
 tr:[['Carica','Se corre 9 m e incorna: +3d6 danni.']],
 act:[['Zoccoli','+6','2d6+4 contundenti',''],['Ascia bipenne','+6','2d6+4 taglienti',''],['Arco lungo','+4','1d8+2 perforanti','']]},
{id:'minotaur',n:'Minotaur',it:'Minotauro',sz:'Grande',t:'mostruosità',ac:14,hp:76,hd:'9d10+27',sp:'12 m',ab:[18,11,16,6,16,9],sk:{perception:7},sen:'Scurovisione 18 m, Percezione passiva 17',cr:'3',
 tr:[['Carica','Se corre 3 m e incorna: +2d8 e TS Forza CD 14 o spinto di 3 m e prono.'],['Memoria del labirinto','Ricorda ogni percorso già fatto.']],
 act:[['Ascia bipenne','+6','2d12+4 taglienti',''],['Incornata','+6','2d8+4 perforanti','']]},
{id:'basilisk',n:'Basilisk',it:'Basilisco',sz:'Media',t:'mostruosità',ac:15,hp:52,hd:'8d8+16',sp:'6 m',ab:[16,8,15,2,8,7],sen:'Scurovisione 18 m, Percezione passiva 9',cr:'3',
 tr:[['Sguardo pietrificante','Chi lo guarda entro 9 m fa TS COS CD 12 o comincia a pietrificarsi.']],
 act:[['Morso','+5','2d6+3 perforanti + 2d6 veleno','']]},
{id:'griffon',n:'Griffon',it:'Grifone',sz:'Grande',t:'mostruosità',ac:12,hp:59,hd:'7d10+21',sp:'9 m, volare 24 m',ab:[18,15,16,2,13,8],sk:{perception:5},sen:'Scurovisione 18 m, Percezione passiva 15',cr:'2',
 tr:[['Vista acuta','Vantaggio alle prove di Percezione basate sulla vista.']],
 act:[['Becco','+6','1d8+4 perforanti',''],['Artigli','+6','2d6+4 taglienti','']]},
{id:'hippogriff',n:'Hippogriff',it:'Ippogrifo',sz:'Grande',t:'mostruosità',ac:11,hp:19,hd:'3d10+3',sp:'12 m, volare 18 m',ab:[17,13,13,2,12,8],sk:{perception:5},sen:'Percezione passiva 15',cr:'1',
 tr:[['Vista acuta','Vantaggio alle prove di Percezione basate sulla vista.']],
 act:[['Becco','+5','1d10+3 perforanti',''],['Artigli','+5','2d6+3 taglienti','']]},
{id:'manticore',n:'Manticore',it:'Mantícora',sz:'Grande',t:'mostruosità',ac:14,hp:68,hd:'8d10+24',sp:'9 m, volare 15 m',ab:[17,16,17,7,12,8],sen:'Scurovisione 18 m, Percezione passiva 11',cr:'3',
 tr:[['Aculei della coda','Ha 24 aculei, che ricrescono con un riposo lungo.']],
 act:[['Morso','+5','1d8+3 perforanti',''],['Artigli','+5','1d6+3 taglienti',''],['Aculeo','+5','1d8+3 perforanti','gittata 30/60 m, tre per attacco']]},
{id:'wyvern',n:'Wyvern',it:'Viverna',sz:'Grande',t:'drago',ac:13,hp:110,hd:'13d10+39',sp:'6 m, volare 24 m',ab:[19,10,16,5,12,6],sk:{perception:4},sen:'Scurovisione 18 m, Percezione passiva 14',cr:'6',
 act:[['Morso','+7','2d6+4 perforanti',''],['Artigli','+7','2d8+4 taglienti',''],['Pungiglione','+7','2d6+4 perforanti + 7d6 veleno','TS COS CD 15 dimezza']]},
{id:'young-red-dragon',n:'Young Red Dragon',it:'Drago rosso giovane',sz:'Grande',t:'drago',ac:18,hp:178,hd:'17d10+85',sp:'12 m, scalare 12 m, volare 24 m',ab:[23,10,21,14,11,19],sk:{perception:6,stealth:4},sen:'Vista cieca 9 m, Scurovisione 36 m, Percezione passiva 16',cr:'10',
 tr:[['Immunità','Immune ai danni da fuoco.']],
 act:[['Morso','+10','2d10+6 perforanti + 1d6 fuoco',''],['Artigli','+10','2d6+6 taglienti','due attacchi'],['Soffio di fuoco','—','16d6 fuoco','Cono di 9 m, TS DES CD 17 dimezza (ricarica 5-6)']]},
{id:'gelatinous-cube',n:'Gelatinous Cube',it:'Cubo gelatinoso',sz:'Grande',t:'melma',ac:6,hp:84,hd:'8d10+40',sp:'4,5 m',ab:[14,3,20,1,6,1],sen:'Visione cieca 18 m, Percezione passiva 8',cr:'2',
 tr:[['Trasparente','Serve una prova di Percezione CD 15 per notarlo prima che attacchi.'],['Assorbire','Entrando nello spazio di una creatura la inghiotte.']],
 act:[['Pseudopodo','+4','3d6 acido','']]},
{id:'mimic',n:'Mimic',it:'Mimic',sz:'Media',t:'mostruosità',ac:12,hp:58,hd:'9d8+18',sp:'4,5 m',ab:[17,12,15,5,13,8],sk:{stealth:5},sen:'Scurovisione 18 m, Percezione passiva 11',cr:'2',
 tr:[['Mutaforma','Assume la forma di un oggetto.'],['Adesivo','Chi lo tocca resta attaccato (CD 13).'],['Falso aspetto','Da immobile è indistinguibile da un oggetto normale.']],
 act:[['Pseudopodo','+5','1d8+3 contundenti + 1d8 acido',''],['Morso','+5','1d8+3 perforanti + 1d8 acido','']]},
{id:'rust-monster',n:'Rust Monster',it:'Mostro della ruggine',sz:'Media',t:'mostruosità',ac:14,hp:27,hd:'5d8+5',sp:'12 m',ab:[13,12,13,2,13,6],sen:'Scurovisione 18 m, Percezione passiva 11',cr:'1/2',
 tr:[['Annusare il ferro','Fiuta il metallo entro 9 m.'],['Distruggere il metallo','Corrode armi e armature non magiche che lo colpiscono.']],
 act:[['Morso','+3','1d8+1 perforanti',''],['Antenne','—','—','Corrode un oggetto di metallo']]},
];
const MONSTER_BY_ID = Object.fromEntries(SRD_MONSTERS.map(m => [m.id, m]));
const CR_ORDER = ['0','1/8','1/4','1/2','1','2','3','4','5','6','10'];
function crValue(cr){ const map = {'0':0,'1/8':0.125,'1/4':0.25,'1/2':0.5}; return map[cr] != null ? map[cr] : (parseFloat(cr)||0); }
function monsterName(m){ return state.spellLang === 'en' ? m.n : m.it; }
