/* ══════════════════════════════════════════════════════════════
   Grimorio — nomi italiani degli incantesimi SRD
   Servono per cercare e leggere in italiano: il testo delle
   descrizioni resta in inglese (è quello ufficiale su licenza OGL).
   Traduzioni d'uso comune al tavolo, non traduzioni ufficiali.
   Puoi correggerne una qualsiasi: basta cambiare la stringa.
   ══════════════════════════════════════════════════════════════ */
const SPELLS_IT = {
  // ── Trucchetti ──
  "acid-splash": "Schizzo Acido",
  "chill-touch": "Tocco Gelido",
  "dancing-lights": "Luci Danzanti",
  "druidcraft": "Arte Druidica",
  "eldritch-blast": "Raggio Occulto",
  "fire-bolt": "Dardo di Fuoco",
  "guidance": "Guida",
  "light": "Luce",
  "mage-hand": "Mano Magica",
  "mending": "Riparare",
  "message": "Messaggio",
  "minor-illusion": "Illusione Minore",
  "poison-spray": "Spruzzo Velenoso",
  "prestidigitation": "Prestidigitazione",
  "produce-flame": "Produrre Fiamma",
  "ray-of-frost": "Raggio di Gelo",
  "resistance": "Resistenza",
  "sacred-flame": "Fiamma Sacra",
  "shillelagh": "Shillelagh",
  "shocking-grasp": "Tocco Folgorante",
  "spare-the-dying": "Risparmiare i Morenti",
  "thaumaturgy": "Taumaturgia",
  "true-strike": "Colpo Certo",
  "vicious-mockery": "Presa in Giro Crudele",

  // ── 1° livello ──
  "alarm": "Allarme",
  "animal-friendship": "Amicizia con gli Animali",
  "bane": "Rovina",
  "bless": "Benedizione",
  "burning-hands": "Mani Brucianti",
  "charm-person": "Charme su Persona",
  "color-spray": "Spruzzo Colorato",
  "command": "Comando",
  "comprehend-languages": "Comprensione dei Linguaggi",
  "create-or-destroy-water": "Creare o Distruggere Acqua",
  "cure-wounds": "Cura Ferite",
  "detect-evil-and-good": "Individuazione del Bene e del Male",
  "detect-magic": "Individuazione del Magico",
  "detect-poison-and-disease": "Individuazione di Veleni e Malattie",
  "disguise-self": "Camuffare Se Stesso",
  "divine-favor": "Favore Divino",
  "entangle": "Intralciare",
  "expeditious-retreat": "Ritirata Rapida",
  "faerie-fire": "Fuoco Fatato",
  "false-life": "Falsa Vita",
  "feather-fall": "Caduta Morbida",
  "find-familiar": "Trovare Famiglio",
  "floating-disk": "Disco Fluttuante di Tenser",
  "fog-cloud": "Nube di Nebbia",
  "goodberry": "Bacca Nutriente",
  "grease": "Grasso",
  "guiding-bolt": "Dardo Guida",
  "healing-word": "Parola Guaritrice",
  "hellish-rebuke": "Rimprovero Infernale",
  "heroism": "Eroismo",
  "hideous-laughter": "Risata Isterica di Tasha",
  "hunters-mark": "Marchio del Cacciatore",
  "identify": "Identificare",
  "illusory-script": "Scritto Illusorio",
  "inflict-wounds": "Infliggere Ferite",
  "jump": "Salto",
  "longstrider": "Passo Lungo",
  "mage-armor": "Armatura Magica",
  "magic-missile": "Dardo Incantato",
  "protection-from-evil-and-good": "Protezione dal Bene e dal Male",
  "purify-food-and-drink": "Purificare Cibo e Bevande",
  "sanctuary": "Santuario",
  "shield": "Scudo",
  "shield-of-faith": "Scudo della Fede",
  "silent-image": "Immagine Silenziosa",
  "sleep": "Sonno",
  "speak-with-animals": "Parlare con gli Animali",
  "thunderwave": "Onda Tonante",
  "unseen-servant": "Servitore Invisibile",

  // ── 2° livello ──
  "acid-arrow": "Freccia Acida di Melf",
  "aid": "Aiuto",
  "alter-self": "Alterare Se Stesso",
  "animal-messenger": "Messaggero Animale",
  "arcane-lock": "Chiusura Arcana",
  "arcanists-magic-aura": "Aura Magica dell'Arcanista",
  "augury": "Presagio",
  "barkskin": "Pelle Cortecciosa",
  "blindness-deafness": "Cecità/Sordità",
  "blur": "Offuscamento",
  "branding-smite": "Colpo Marchiante",
  "calm-emotions": "Calmare Emozioni",
  "continual-flame": "Fiamma Perenne",
  "darkness": "Oscurità",
  "darkvision": "Scurovisione",
  "detect-thoughts": "Individuazione dei Pensieri",
  "enhance-ability": "Potenziare Caratteristica",
  "enlarge-reduce": "Ingrandire/Ridurre",
  "enthrall": "Soggiogare",
  "find-steed": "Trovare Destriero",
  "find-traps": "Trovare Trappole",
  "flame-blade": "Lama Infuocata",
  "flaming-sphere": "Sfera Infuocata",
  "gentle-repose": "Riposo Tranquillo",
  "gust-of-wind": "Raffica di Vento",
  "heat-metal": "Riscaldare il Metallo",
  "hold-person": "Blocca Persone",
  "invisibility": "Invisibilità",
  "knock": "Apertura",
  "lesser-restoration": "Ristorare Inferiore",
  "levitate": "Levitazione",
  "locate-animals-or-plants": "Individuare Animali o Piante",
  "locate-object": "Individuare Oggetti",
  "magic-mouth": "Bocca Magica",
  "magic-weapon": "Arma Magica",
  "mirror-image": "Immagine Speculare",
  "misty-step": "Passo Velato",
  "moonbeam": "Raggio di Luna",
  "pass-without-trace": "Passo senza Tracce",
  "prayer-of-healing": "Preghiera di Guarigione",
  "protection-from-poison": "Protezione dal Veleno",
  "ray-of-enfeeblement": "Raggio di Indebolimento",
  "rope-trick": "Trucco della Corda",
  "scorching-ray": "Raggio Rovente",
  "see-invisibility": "Vedere Invisibilità",
  "shatter": "Frantumare",
  "silence": "Silenzio",
  "spider-climb": "Passo del Ragno",
  "spike-growth": "Crescita di Spine",
  "spiritual-weapon": "Arma Spirituale",
  "suggestion": "Suggestione",
  "warding-bond": "Legame Protettivo",
  "web": "Ragnatela",
  "zone-of-truth": "Zona di Verità",

  // ── 3° livello ──
  "animate-dead": "Animare Morti",
  "beacon-of-hope": "Faro di Speranza",
  "bestow-curse": "Infliggere Maledizione",
  "blink": "Balenare",
  "call-lightning": "Evocare Fulmini",
  "clairvoyance": "Chiaroveggenza",
  "conjure-animals": "Evocare Animali",
  "counterspell": "Controincantesimo",
  "create-food-and-water": "Creare Cibo e Acqua",
  "daylight": "Luce del Giorno",
  "dispel-magic": "Dissolvi Magie",
  "fear": "Paura",
  "fireball": "Palla di Fuoco",
  "fly": "Volare",
  "gaseous-form": "Forma Gassosa",
  "glyph-of-warding": "Glifo di Protezione",
  "haste": "Velocità",
  "hypnotic-pattern": "Schema Ipnotico",
  "lightning-bolt": "Fulmine",
  "magic-circle": "Cerchio Magico",
  "major-image": "Immagine Maggiore",
  "mass-healing-word": "Parola Guaritrice di Massa",
  "meld-into-stone": "Fondersi con la Pietra",
  "nondetection": "Non Individuazione",
  "phantom-steed": "Destriero Fantasma",
  "plant-growth": "Crescita Vegetale",
  "protection-from-energy": "Protezione dall'Energia",
  "remove-curse": "Rimuovi Maledizione",
  "revivify": "Rianimare",
  "sending": "Messaggio Trasmesso",
  "sleet-storm": "Tempesta di Nevischio",
  "slow": "Lentezza",
  "speak-with-dead": "Parlare con i Morti",
  "speak-with-plants": "Parlare con le Piante",
  "spirit-guardians": "Guardiani Spirituali",
  "stinking-cloud": "Nube Maleodorante",
  "tiny-hut": "Piccola Capanna di Leomund",
  "tongues": "Lingue",
  "vampiric-touch": "Tocco Vampirico",
  "water-breathing": "Respirare sott'Acqua",
  "water-walk": "Camminare sull'Acqua",
  "wind-wall": "Muro di Vento",

  // ── 4° livello ──
  "arcane-eye": "Occhio Arcano",
  "banishment": "Bandire",
  "black-tentacles": "Tentacoli Neri di Evard",
  "blight": "Piaga",
  "compulsion": "Coercizione",
  "confusion": "Confusione",
  "conjure-minor-elementals": "Evocare Elementali Minori",
  "conjure-woodland-beings": "Evocare Creature Silvane",
  "control-water": "Controllare l'Acqua",
  "death-ward": "Protezione dalla Morte",
  "dimension-door": "Porta Dimensionale",
  "divination": "Divinazione",
  "dominate-beast": "Dominare Bestie",
  "fabricate": "Fabbricare",
  "faithful-hound": "Segugio Fedele di Mordenkainen",
  "fire-shield": "Scudo di Fuoco",
  "freedom-of-movement": "Libertà di Movimento",
  "giant-insect": "Insetto Gigante",
  "greater-invisibility": "Invisibilità Superiore",
  "guardian-of-faith": "Guardiano della Fede",
  "hallucinatory-terrain": "Terreno Allucinatorio",
  "ice-storm": "Tempesta di Ghiaccio",
  "locate-creature": "Individuare Creature",
  "phantasmal-killer": "Assassino Fantasma",
  "polymorph": "Metamorfosi",
  "private-sanctum": "Sacrario Privato di Mordenkainen",
  "resilient-sphere": "Sfera Resiliente di Otiluke",
  "secret-chest": "Cassa Segreta di Leomund",
  "stone-shape": "Modellare la Pietra",
  "stoneskin": "Pelle di Pietra",
  "wall-of-fire": "Muro di Fuoco",

  // ── 5° livello ──
  "animate-objects": "Animare Oggetti",
  "antilife-shell": "Guscio Antivita",
  "arcane-hand": "Mano Arcana di Bigby",
  "awaken": "Risvegliare",
  "cloudkill": "Nube Mortale",
  "commune": "Comunione",
  "commune-with-nature": "Comunione con la Natura",
  "cone-of-cold": "Cono di Freddo",
  "conjure-elemental": "Evocare Elementale",
  "contact-other-plane": "Contattare Altri Piani",
  "contagion": "Contagio",
  "creation": "Creazione",
  "dispel-evil-and-good": "Dissolvi il Bene e il Male",
  "dominate-person": "Dominare Persone",
  "dream": "Sogno",
  "flame-strike": "Colonna di Fuoco",
  "geas": "Costrizione",
  "greater-restoration": "Ristorare Superiore",
  "hallow": "Consacrare",
  "hold-monster": "Blocca Mostri",
  "insect-plague": "Piaga d'Insetti",
  "legend-lore": "Leggenda",
  "mass-cure-wounds": "Cura Ferite di Massa",
  "mislead": "Ingannare",
  "modify-memory": "Modificare Memoria",
  "passwall": "Passapareti",
  "planar-binding": "Legame Planare",
  "raise-dead": "Rianimare Morti",
  "reincarnate": "Reincarnare",
  "scrying": "Scrutare",
  "seeming": "Apparenza",
  "telekinesis": "Telecinesi",
  "telepathic-bond": "Legame Telepatico di Rary",
  "teleportation-circle": "Cerchio di Teletrasporto",
  "tree-stride": "Passo Arboreo",
  "wall-of-force": "Muro di Forza",
  "wall-of-stone": "Muro di Pietra",

  // ── 6° livello ──
  "blade-barrier": "Barriera di Lame",
  "chain-lightning": "Fulmine a Catena",
  "circle-of-death": "Cerchio della Morte",
  "conjure-fey": "Evocare Folletti",
  "contingency": "Contingenza",
  "create-undead": "Creare Non Morti",
  "disintegrate": "Disintegrare",
  "eyebite": "Malocchio",
  "find-the-path": "Trovare il Sentiero",
  "flesh-to-stone": "Pietrificare",
  "forbiddance": "Interdizione",
  "freezing-sphere": "Sfera Congelante di Otiluke",
  "globe-of-invulnerability": "Globo di Invulnerabilità",
  "guards-and-wards": "Guardie e Custodi",
  "harm": "Ferire",
  "heal": "Guarigione",
  "heroes-feast": "Banchetto degli Eroi",
  "instant-summons": "Convocazione Istantanea di Drawmij",
  "irresistible-dance": "Danza Irresistibile di Otto",
  "magic-jar": "Vaso Magico",
  "mass-suggestion": "Suggestione di Massa",
  "move-earth": "Muovere il Terreno",
  "planar-ally": "Alleato Planare",
  "programmed-illusion": "Illusione Programmata",
  "sunbeam": "Raggio di Sole",
  "transport-via-plants": "Trasporto Vegetale",
  "true-seeing": "Visione del Vero",
  "wall-of-ice": "Muro di Ghiaccio",
  "wall-of-thorns": "Muro di Spine",
  "wind-walk": "Camminare nel Vento",
  "word-of-recall": "Parola del Richiamo",

  // ── 7° livello ──
  "arcane-sword": "Spada Arcana di Mordenkainen",
  "conjure-celestial": "Evocare Celestiale",
  "delayed-blast-fireball": "Palla di Fuoco Ritardata",
  "divine-word": "Parola Divina",
  "etherealness": "Etereità",
  "finger-of-death": "Dito della Morte",
  "fire-storm": "Tempesta di Fuoco",
  "forcecage": "Gabbia di Forza",
  "magnificent-mansion": "Magione Magnifica di Mordenkainen",
  "mirage-arcane": "Miraggio Arcano",
  "plane-shift": "Spostamento Planare",
  "prismatic-spray": "Spruzzo Prismatico",
  "project-image": "Proiettare Immagine",
  "regenerate": "Rigenerare",
  "resurrection": "Resurrezione",
  "reverse-gravity": "Invertire la Gravità",
  "sequester": "Segregare",
  "simulacrum": "Simulacro",
  "symbol": "Simbolo",
  "teleport": "Teletrasporto",

  // ── 8° livello ──
  "animal-shapes": "Forme Animali",
  "antimagic-field": "Campo Antimagia",
  "antipathy-sympathy": "Antipatia/Simpatia",
  "clone": "Clone",
  "control-weather": "Controllare il Clima",
  "demiplane": "Semipiano",
  "dominate-monster": "Dominare Mostri",
  "earthquake": "Terremoto",
  "feeblemind": "Mente Ottenebrata",
  "glibness": "Parlantina",
  "holy-aura": "Aura Sacra",
  "incendiary-cloud": "Nube Incendiaria",
  "maze": "Labirinto",
  "mind-blank": "Schermo Mentale",
  "power-word-stun": "Parola del Potere: Stordire",
  "sunburst": "Esplosione Solare",

  // ── 9° livello ──
  "astral-projection": "Proiezione Astrale",
  "foresight": "Preveggenza",
  "gate": "Portale",
  "imprisonment": "Imprigionamento",
  "mass-heal": "Guarigione di Massa",
  "meteor-swarm": "Sciame di Meteore",
  "power-word-kill": "Parola del Potere: Uccidere",
  "prismatic-wall": "Muro Prismatico",
  "shapechange": "Mutare Forma",
  "storm-of-vengeance": "Tempesta della Vendetta",
  "time-stop": "Arresto del Tempo",
  "true-polymorph": "Metamorfosi Superiore",
  "true-resurrection": "Resurrezione Pura",
  "weird": "Visione Terrificante",
  "wish": "Desiderio"
};
